export type RolePreviewValue = {
  category: string;
  level: "Foundation" | "Professional" | "Leadership";
  ecosystems: string[];
  previewValue: string;
};

// Extracted from IFU_ROLES BASED Discovery_Site_Content_Fix_Package For Developer RECOMMENDED-FINAL.docx.
export const rolePreviewValuesByTitle: Record<string, RolePreviewValue> = {
  "Agri-Logistics Founder": {
    category: "Entrepreneurs & Innovators",
    level: "Leadership",
    ecosystems: ["AgriExchange", "AgriCentral", "AgriFinance"],
    previewValue: "Plug into AgriExchange order flows, coordinate with farm operations via AgriCentral, and settle payments through AgriFinance.",
  },
  "Agri-Tech Startup Founder": {
    category: "Entrepreneurs & Innovators",
    level: "Leadership",
    ecosystems: ["AgriCapital", "AgriExchange", "AgriNexus"],
    previewValue: "Investor connections in AgriCapital, a route to market through AgriExchange, and the founder community in AgriNexus.",
  },
  "Agricultural Data Scientist": {
    category: "Research & Academia",
    level: "Professional",
    ecosystems: ["AgriSphere", "AgriFinance", "AgriCentral"],
    previewValue: "Work with aggregated agricultural datasets from AgriSphere, financial models in AgriFinance, and operational farm data via AgriCentral.",
  },
  "Agricultural Economist": {
    category: "Agricultural Professionals",
    level: "Professional",
    ecosystems: ["AgriSphere", "AgriExchange", "AgriCapital"],
    previewValue: "Market and price analytics in AgriSphere and AgriExchange, plus investment and financing trend data through AgriCapital.",
  },
  "Agricultural Extension Officer": {
    category: "Government & Public Sector",
    level: "Professional",
    ecosystems: ["AgriCentral", "AgriAcademie", "AgriNexus"],
    previewValue: "Manage farmer outreach in AgriCentral, deliver training content through AgriAcademie, and stay connected to your farmer network in AgriNexus.",
  },
  "Agricultural Input Supplier": {
    category: "Agri-Business & Trade",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriNexus", "AgriSphere"],
    previewValue: "A farmer-direct sales channel on AgriExchange, demand intelligence from AgriSphere, and co-branded farmer education via AgriNexus.",
  },
  "Agricultural Insurance Agent": {
    category: "Finance & Investment",
    level: "Professional",
    ecosystems: ["AgriShield", "AgriCentral", "AgriFinance"],
    previewValue: "Crop and livestock risk data through AgriShield, insured-farm records via AgriCentral, and premium payment processing in AgriFinance.",
  },
  "Agricultural Journalist": {
    category: "Media & Communications",
    level: "Professional",
    ecosystems: ["AgriSphere", "AgriNexus"],
    previewValue: "Market intelligence and country reports in AgriSphere plus a verified expert-source network in AgriNexus for stories that matter.",
  },
  "Agricultural Policy Analyst": {
    category: "Government & Public Sector",
    level: "Professional",
    ecosystems: ["AgriSphere", "AgriShield"],
    previewValue: "Cross-country agricultural data and trends in AgriSphere plus regulatory landscape monitoring in AgriShield for evidence-based policy work.",
  },
  "Agricultural Researcher": {
    category: "Research & Academia",
    level: "Professional",
    ecosystems: ["AgriSphere", "AgriAcademie", "AgriNexus"],
    previewValue: "Anonymised platform datasets and country intelligence in AgriSphere, publication and course channels on AgriAcademie, and research networks in AgriNexus.",
  },
  "Agritourism Host": {
    category: "Farmers & Producers",
    level: "Professional",
    ecosystems: ["AgriTourisme", "AgriFinance", "AgriSphere"],
    previewValue: "List farm stays and experiences on AgriTourisme, take bookings and payments through AgriFinance, and reach global visitors via AgriSphere.",
  },
  "Agronomist": {
    category: "Agricultural Professionals",
    level: "Professional",
    ecosystems: ["AgriCentral", "AgriAcademie", "AgriNexus"],
    previewValue: "Advise farms through AgriCentral, publish courses on AgriAcademie, and build your expert profile and client network in AgriNexus.",
  },
  "Aquaculture Farmer": {
    category: "Farmers & Producers",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriCapital", "AgriCentral"],
    previewValue: "Seafood market access on AgriExchange, aquaculture investment opportunities in AgriCapital, and pond and stock records in AgriCentral.",
  },
  "Carbon Credit Specialist": {
    category: "Sustainability & AgriFuture",
    level: "Professional",
    ecosystems: ["AgriSphere", "AgriShield", "AgriExchange"],
    previewValue: "Land and practice data from AgriSphere, verification workflows in AgriShield, and future carbon credit trading on AgriExchange.",
  },
  "Certification Auditor": {
    category: "Compliance & Certification",
    level: "Professional",
    ecosystems: ["AgriShield", "AgriCentral"],
    previewValue: "Audit workflows and certification records in AgriShield, backed by farm operational documentation from AgriCentral.",
  },
  "Climate-Smart Agriculture Coordinator": {
    category: "NGOs & Foundations",
    level: "Professional",
    ecosystems: ["AgriSphere", "AgriAcademie", "AgriFunds"],
    previewValue: "Climate-zone data in AgriSphere, climate-smart training delivery via AgriAcademie, and adaptation program funding through AgriFunds.",
  },
  "Cocoa Farmer": {
    category: "Farmers & Producers",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriShield", "AgriSphere"],
    previewValue: "Cocoa buyer connections on AgriExchange, traceability and certification support in AgriShield, and world price feeds in AgriSphere.",
  },
  "Coffee Farmer": {
    category: "Farmers & Producers",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriSphere", "AgriAcademie"],
    previewValue: "Specialty coffee buyers on AgriExchange, origin-market price intelligence in AgriSphere, and quality and cupping training in AgriAcademie.",
  },
  "Cold Chain & Storage Manager": {
    category: "Agri-Business & Trade",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriCentral"],
    previewValue: "Connect storage capacity to AgriExchange order flows and manage facility operations and staffing through AgriCentral.",
  },
  "Commercial Farmer": {
    category: "Farmers & Producers",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriCentral", "AgriFinance", "AgriSphere"],
    previewValue: "Sell at scale on AgriExchange, run operations and workers in AgriCentral, and manage invoices and accounting in AgriFinance - one login for the whole farm business.",
  },
  "Commodity Trader": {
    category: "Agri-Business & Trade",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriSphere", "AgriFinance"],
    previewValue: "A global commodity marketplace on AgriExchange, real-time price feeds in AgriSphere, and trade settlement through AgriFinance.",
  },
  "Cooperative Accountant": {
    category: "Cooperatives & Associations",
    level: "Professional",
    ecosystems: ["AgriFinance", "AgriCentral"],
    previewValue: "Cooperative bookkeeping, member payment records, and QuickBooks/Xero/Sage integrations in AgriFinance, tied to member data in AgriCentral.",
  },
  "Cooperative Leader": {
    category: "Cooperatives & Associations",
    level: "Leadership",
    ecosystems: ["AgriCentral", "AgriExchange", "AgriFinance", "AgriNexus"],
    previewValue: "A multi-farm dashboard in AgriCentral, group selling power on AgriExchange, cooperative accounts in AgriFinance, and member engagement in AgriNexus.",
  },
  "Cooperative Member": {
    category: "Cooperatives & Associations",
    level: "Foundation",
    ecosystems: ["AgriExchange", "AgriNexus", "AgriAcademie"],
    previewValue: "Access your cooperative's negotiated rates on AgriExchange, connect with fellow members in AgriNexus, and use shared training in AgriAcademie.",
  },
  "Crop Credit Analyst": {
    category: "Finance & Investment",
    level: "Professional",
    ecosystems: ["AgriFinance", "AgriSphere"],
    previewValue: "Farm-level financial health models in AgriFinance combined with crop, weather, and market risk data from AgriSphere.",
  },
  "Customs & Trade Officer": {
    category: "Government & Public Sector",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriShield"],
    previewValue: "Visibility into cross-border agricultural trade flows on AgriExchange and export/import compliance frameworks in AgriShield.",
  },
  "Dairy Farmer": {
    category: "Farmers & Producers",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriCentral", "AgriFinance"],
    previewValue: "Daily production records in AgriCentral, buyer connections for milk and dairy on AgriExchange, and payment tracking in AgriFinance.",
  },
  "Development Finance Officer": {
    category: "Finance & Investment",
    level: "Leadership",
    ecosystems: ["AgriCapital", "AgriFunds", "AgriSphere"],
    previewValue: "Pipeline of investable agricultural projects in AgriCapital, blended-finance and grant co-funding through AgriFunds, and country data in AgriSphere.",
  },
  "Equipment Distributor": {
    category: "Agri-Business & Trade",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriCentral", "AgriCapital"],
    previewValue: "Reach mechanising farms via AgriExchange, integrate with AgriCentral equipment records, and offer financing through AgriCapital partners.",
  },
  "Exporter / Importer": {
    category: "Agri-Business & Trade",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriShield", "AgriFinance"],
    previewValue: "Cross-border deal flow on AgriExchange, export compliance documentation in AgriShield, and multi-currency settlement in AgriFinance.",
  },
  "Farm Business Consultant": {
    category: "Agricultural Professionals",
    level: "Professional",
    ecosystems: ["AgriFinance", "AgriCentral", "AgriNexus"],
    previewValue: "Client farm financials through AgriFinance, operational data in AgriCentral, and a consulting practice profile in AgriNexus.",
  },
  "Farm Content Creator": {
    category: "Media & Communications",
    level: "Foundation",
    ecosystems: ["AgriNexus", "AgriTourisme", "AgriAcademie"],
    previewValue: "Build your audience in AgriNexus, monetise farm visits through AgriTourisme, and publish paid educational content on AgriAcademie.",
  },
  "Farm-to-Table Business Owner": {
    category: "Entrepreneurs & Innovators",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriTourisme", "AgriNexus"],
    previewValue: "Source verified local produce on AgriExchange, list culinary farm experiences on AgriTourisme, and build supplier relationships in AgriNexus.",
  },
  "Food Processor & Manufacturer": {
    category: "Agri-Business & Trade",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriShield", "AgriSphere"],
    previewValue: "Direct farmer sourcing at scale on AgriExchange, traceability and food-safety compliance in AgriShield, and commodity price intelligence in AgriSphere.",
  },
  "Food Safety Inspector": {
    category: "Compliance & Certification",
    level: "Professional",
    ecosystems: ["AgriShield", "AgriExchange"],
    previewValue: "Food safety compliance monitoring in AgriShield with full traceability into AgriExchange supply chains.",
  },
  "Food Security Programme Manager": {
    category: "NGOs & Foundations",
    level: "Leadership",
    ecosystems: ["AgriSphere", "AgriFunds", "AgriExchange"],
    previewValue: "Food security intelligence across 190+ countries in AgriSphere, program funding in AgriFunds, and supply-chain linkages via AgriExchange.",
  },
  "FoodTech Entrepreneur": {
    category: "Entrepreneurs & Innovators",
    level: "Leadership",
    ecosystems: ["AgriExchange", "AgriCapital", "AgriSphere"],
    previewValue: "Source directly from farmers on AgriExchange, raise through AgriCapital, and size markets with AgriSphere intelligence.",
  },
  "Foundation Program Officer": {
    category: "NGOs & Foundations",
    level: "Leadership",
    ecosystems: ["AgriFunds", "AgriSphere", "AgriCapital"],
    previewValue: "Grant program management and impact dashboards in AgriFunds, country intelligence in AgriSphere, and co-investment visibility through AgriCapital.",
  },
  "Grain & Cereal Farmer": {
    category: "Farmers & Producers",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriSphere", "AgriFinance"],
    previewValue: "Global grain buyers on AgriExchange, live commodity price feeds in AgriSphere, and trade bookkeeping in AgriFinance.",
  },
  "Horticulture Farmer": {
    category: "Farmers & Producers",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriTourisme", "AgriCentral"],
    previewValue: "Fresh produce buyers on AgriExchange, farm-visit and pick-your-own income through AgriTourisme, and harvest scheduling in AgriCentral.",
  },
  "IFU Country Representative": {
    category: "Country & Regional Leadership",
    level: "Leadership",
    ecosystems: ["All 10 ecosystems"],
    previewValue: "Full country dashboard, member onboarding tools, government relations support, and reporting across all 10 IFU ecosystems for your country.",
  },
  "Impact Investor": {
    category: "Finance & Investment",
    level: "Leadership",
    ecosystems: ["AgriCapital", "AgriFinance", "AgriSphere"],
    previewValue: "Curated agricultural deal flow in AgriCapital, farm financial health scoring via AgriFinance, and market context from AgriSphere - with ESG impact reporting built in.",
  },
  "Irrigation Engineer": {
    category: "Agricultural Professionals",
    level: "Professional",
    ecosystems: ["AgriCentral", "AgriSphere", "AgriNexus"],
    previewValue: "Water-management projects through AgriCentral, climate and rainfall intelligence in AgriSphere, and client connections in AgriNexus.",
  },
  "Livestock Farmer": {
    category: "Farmers & Producers",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriCentral", "AgriShield"],
    previewValue: "List livestock on AgriExchange, track herd records and workers in AgriCentral, and stay compliant with animal-health rules through AgriShield.",
  },
  "Microfinance Officer": {
    category: "Finance & Investment",
    level: "Professional",
    ecosystems: ["AgriCapital", "AgriFinance", "AgriCentral"],
    previewValue: "AI-assisted farmer credit scoring through AgriFinance, loan pipeline management in AgriCapital, and borrower farm data via AgriCentral.",
  },
  "Ministry of Agriculture Official": {
    category: "Government & Public Sector",
    level: "Leadership",
    ecosystems: ["AgriSphere", "AgriShield", "AgriCentral"],
    previewValue: "A national agricultural intelligence dashboard in AgriSphere, policy compliance visibility through AgriShield, and program delivery data from AgriCentral.",
  },
  "NGO Field Officer": {
    category: "NGOs & Foundations",
    level: "Professional",
    ecosystems: ["AgriFunds", "AgriCentral", "AgriNexus"],
    previewValue: "Field data collection through AgriCentral, program funding and disbursement tracking in AgriFunds, and community engagement in AgriNexus.",
  },
  "Organic Farmer": {
    category: "Farmers & Producers",
    level: "Professional",
    ecosystems: ["AgriShield", "AgriExchange", "AgriAcademie"],
    previewValue: "Organic certification tracking in AgriShield, premium organic buyer channels on AgriExchange, and organic methods courses in AgriAcademie.",
  },
  "Plant Genetics Researcher": {
    category: "Research & Academia",
    level: "Professional",
    ecosystems: ["AgriSphere", "AgriAcademie", "AgriNexus"],
    previewValue: "Crop variety and climate-zone data in AgriSphere, research dissemination through AgriAcademie, and collaboration networks in AgriNexus.",
  },
  "Post-Harvest Specialist": {
    category: "Agricultural Professionals",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriCentral", "AgriAcademie"],
    previewValue: "Reduce losses between farm and market with AgriExchange logistics data, AgriCentral storage records, and loss-prevention training on AgriAcademie.",
  },
  "Poultry Farmer": {
    category: "Farmers & Producers",
    level: "Professional",
    ecosystems: ["AgriExchange", "AgriCentral", "AgriShield"],
    previewValue: "Flock management in AgriCentral, direct buyer access on AgriExchange, and biosecurity compliance guidance in AgriShield.",
  },
  "Precision Agriculture Specialist": {
    category: "Agricultural Professionals",
    level: "Professional",
    ecosystems: ["AgriCentral", "AgriSphere", "AgriNexus"],
    previewValue: "Bring drone, sensor, and satellite insight to farms through AgriCentral, layered on AgriSphere mapping, with clients found in AgriNexus.",
  },
  "Regenerative Agriculture Specialist": {
    category: "Sustainability & AgriFuture",
    level: "Professional",
    ecosystems: ["AgriAcademie", "AgriCentral", "AgriSphere"],
    previewValue: "Teach regenerative methods on AgriAcademie, track practice adoption through AgriCentral, and measure outcomes with AgriSphere data.",
  },
  "Rural Bank Officer": {
    category: "Finance & Investment",
    level: "Professional",
    ecosystems: ["AgriFinance", "AgriCapital", "AgriCentral"],
    previewValue: "Farm financial statements and health scores in AgriFinance, agricultural lending products through AgriCapital, and portfolio farm visibility in AgriCentral.",
  },
  "Rural Development Officer": {
    category: "Government & Public Sector",
    level: "Professional",
    ecosystems: ["AgriSphere", "AgriFunds", "AgriCentral"],
    previewValue: "Region-level intelligence in AgriSphere, development program funding pipelines in AgriFunds, and delivery tracking in AgriCentral.",
  },
  "Smallholder Farmer": {
    category: "Farmers & Producers",
    level: "Foundation",
    ecosystems: ["AgriSphere", "AgriAcademie", "AgriNexus"],
    previewValue: "Free platform access with agricultural training in AgriAcademie, community support in AgriNexus, and country market intelligence in AgriSphere - built for farms of every size.",
  },
  "Soil Scientist": {
    category: "Agricultural Professionals",
    level: "Professional",
    ecosystems: ["AgriSphere", "AgriCentral", "AgriAcademie"],
    previewValue: "Soil and climate-zone data in AgriSphere, farm-level diagnostics through AgriCentral, and farmer education publishing on AgriAcademie.",
  },
  "University Professor": {
    category: "Research & Academia",
    level: "Leadership",
    ecosystems: ["AgriAcademie", "AgriNexus", "AgriSphere"],
    previewValue: "Publish certified courses on AgriAcademie, manage student cohorts, connect with global peers in AgriNexus, and draw on AgriSphere datasets.",
  },
  "Veterinarian": {
    category: "Agricultural Professionals",
    level: "Professional",
    ecosystems: ["AgriCentral", "AgriNexus", "AgriAcademie"],
    previewValue: "Livestock health records via AgriCentral, an expert practice profile in AgriNexus, and veterinary training content on AgriAcademie.",
  },
  "Women's Cooperative Lead": {
    category: "Cooperatives & Associations",
    level: "Leadership",
    ecosystems: ["AgriNexus", "AgriFunds", "AgriAcademie"],
    previewValue: "Women-in-agriculture networks in AgriNexus, targeted grant programs in AgriFunds, and leadership training in AgriAcademie.",
  },
};
